version: '3'

name: backend-nestjs-ecommerce

services:
  database:
    image: mysql:8
    container_name: database-ecommerce
    restart: always
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    ports:
      - ${DB_PORT}:3306

  cache:
    image: redis:7
    container_name: redis-ecommerce
    restart: always
    ports:
      - ${REDIS_PORT}:6379
